### ISSUE TITLE
Print 3d freecodecamp logo

### ISSUE THREAD

**Issue by ojongerius** [freecodecamp-wellington/freecodecamp-wellington.github.io#19]
It would be awesome to use the 3D printers at the National Library to print a 3d version of the freeCodeCamp logo.

Cost would be 4 NZD, a steal!

**Comment by putara** [comment]
I've been modelling a 3D logo using Blender.
[Demo](https://putara.github.io/3d/) (mesh files are very big! LQ is about **2MB**, HQ is about **7MB**)

According to [the library website](https://natlib.govt.nz/visiting/wellington/3d-printing),

- three 3D printers available
- $4 = $3 per print + $1 per hour for iMac
- 12cm x 12cm x 12cm (a CD is 12cm in diameter)
- only STL format is accepted

I have no idea how long it takes to print a model. And I may need more than $4 for tryouts. :sweat_smile:

Here's some tips for [modelling](https://www.shapeways.com/tutorials/prepping_blender_files_for_3d_printing) and [exporting](https://www.shapeways.com/tutorials/exporting-from-blender) for 3D printing.
If someone needs my Blender files, I'll upload them somewhere.

**Comment by ojongerius** [comment]
Has been done and printed by @putara, nice work dude!
